camunda.bpm.admin-user:
  id: Alex
  password: asd

spring:
  datasource:
    url: jdbc:h2:file:/Users/alexandereuler/Projects/FH/sehanalyse/db/camundaDB

email:
  host: mail.fh-muenster.de
  sender: donotreply@fh-muenster.de